### ISSUE TITLE
2018-08-09-googling-errors-1.md Python stack trace images replicated

### ISSUE THREAD

**Issue by ben-sandham** [GeeWee/geewee.github.io#10]
Hello, I was reading the How to Read Programming Error Messages article and noticed that the images used for the Python stack trace/traceback are duplicated. The second image should be the annotated image.

**Comment by GeeWee** [comment]
Good catch - let me get right on fixing that. Thanks!

**Comment by GeeWee** [comment]
Seems like it is annotated - it's just with comments. It's not as clear as the above image for sure though. I'll keep that in mind. Thanks for reaching out :)
